services:
  # assets-service:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    #   target: Development
    # container_name: Backend_assets-service
    # volumes:
    #   - .:/usr/apps
    #   - /usr/apps/node_modules
    # networks:
    #   - apps
    # environment:
    #   - NODE_ENV=development
    #   - PORT=3200
    #   - GLOBAL_PREFIX=assets-service
    #   - MONGODB_URI=mongodb://mongoDb:27017
    # ports:
    #   - 3200:3200
    # command: nx serve assets-service
    # depends_on:
    #   mongoDb:
    #     condition: service_healthy
  mongoDb:
    container_name: Backend_mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    mem_limit: 1g
    networks:
      - apps
    # healthcheck:
    #   test: "exit 0"
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
networks:
  apps:
    name: apps
    driver: bridge